//standard widgets
import { VerticalBox, Button , HorizontalBox } from "std-widgets.slint";
//custom widget and theme colors
import { Screen } from "widgets\\screen.slint";
import { Palette } from "color\\palette.slint";
import { Toolbar, ToolbarCallbacks } from "widgets\\toolbar.slint";

component LVIE inherits Window {

    title: "LVIE";

    background: Palette.Dark.Dark-100;

    preferred-height: 600px;
    preferred-width: 1000px;

    tb := Toolbar {
        height: 40px;
        width: root.width;
        x: 0px;
        y: 0px;
    }

    in-out property <image> image <=> content.image;

    content := Screen {
        height: root.height - tb.height;
        width: root.width;
        x: 0px;
        y: tb.height;
    }
}

export { LVIE, ToolbarCallbacks }