//standard widgets
import { VerticalBox, Button , HorizontalBox } from "std-widgets.slint";
//custom widget and theme colors
import { Screen, ScreenCallbacks, Linespace, MaskCallbacks, CurveCallbacks } from "widgets/screen.slint";
import { Palette } from "color/palette.slint";
import { Toolbar, ToolbarCallbacks, Spacer, AlertType } from "widgets/toolbar.slint";

component LVIE inherits Window {
    title: "LVIE";

    background: Palette.Dark.Dark-100;

    preferred-width: 1000px;
    preferred-height: 1000px * 9 / 16;

    padding: 0;

    in-out property <AlertType> AlertBoxType: AlertType.Null;
    in-out property <string> AlertText: "";

    in-out property <[string]> svg_path;
    in-out property <[image]> new_histogram;

    in-out property <image> image <=> content.image;
    in-out property <image> curve <=> content.curve;
    
    in-out property <[[float]]> curve_points <=> content.curve_points;
    in-out property <[[float]]> mask_points <=> content.mask_points;
    in-out property <[[float]]> bezier_control_points <=> content.bezier_control_points;
    in-out property <[[float]]> connection_line_points <=> content.connection_line;
    in-out property <[[float]]> control_point_connection_line <=> content.control_point_connection_line;

    in-out property <physical-length> image-space-size-width: content.image-space-size-width;

    callback handle-shortcut(string, bool, bool, bool);

    key_handler := FocusScope {

        tb := Toolbar {
            AlertBoxType: AlertBoxType;
            AlertText: AlertText;
            height: 40px;
            width: root.width;
            x: 0px;
            y: 0px;
        }

        Spacer {
            bgcolor: Palette.Dark.Dark-200;
            x: 10px;
            y: tb.height;
            width: root.width - 20px;
        }

        

        content := Screen {
            histogram: svg-path;
            new_histogram: new_histogram;
            height: root.height - tb.height;
            width: root.width;
            x: 0px;
            y: tb.height;
        }


        key-pressed(event) => {
            handle-shortcut(event.text, event.modifiers.alt, event.modifiers.control, event.modifiers.shift);
            return EventResult.accept;
        }
    }

    init => {
        key-handler.focus();
    }
}

export { LVIE, ToolbarCallbacks, ScreenCallbacks, Linespace, MaskCallbacks, CurveCallbacks }