import { Palette } from "..\\..\\color\\palette.slint";

component ProgressBar inherits Rectangle {
    in-out property <percent> percentage: 0%;
    in property <color> bar_color;

    function set_percentage(value: percent) {
        self.percentage = value;
    }

    background: Palette.Dark.Dark-200;

    height: 4px;
    border-radius: self.height;
    Rectangle {
        x: parent.x;
        y: parent.y;
        height: parent.height;
        width: parent.width * percentage;
        background: bar-color;
    }
}

export { ProgressBar }