import { VerticalBox, ScrollView } from "std-widgets.slint";
import { Palette } from "..\\..\\color\\palette.slint";

component Spacer inherits Rectangle {
    in property <length> size: 1px;
    in property <color> bgcolor: Palette.Dark.Dark-100;
    height: size;
    background: bgcolor;
    border-radius: size * 10%;
}

component MenuItem inherits VerticalBox {
    callback item-callback();

    in-out property <string> text;

    padding: 0;
    spacing: 1px;
    Rectangle {
        height: 30px;
        background: transparent;
        padding: 3px;

        @children

        if text != "" : text_area := Text {
                font-size: 15px;
                text: text;
                x: parent.padding;
                y: parent.padding;
            }

        TouchArea {
            clicked => { item-callback() }
        }
    }

}

component PopupMenu inherits PopupWindow {
    width: 200px;

    in-out property <color> background: Palette.Dark.Dark-300;

    Rectangle {
        height: parent.height;
        width: parent.width;
        background: parent.background;
        border-radius: 7px;
        border-color: black;
        border-width: 1px;
        VerticalBox {
            spacing: 3px;
            height: parent.height;
            width: parent.width;
            @children
        }
    }
}

export { PopupMenu, MenuItem, Spacer }