[package]
name = "LVIElib"
version = "0.1.0"
edition = "2021"

[lib]
name = "LVIElib"

[dependencies]
rustfft = "6.1.0"
transpose = "0.2.2"
image = "0.24.7"
num-traits = "0.2.16"
nalgebra = "0.32.3"
rayon = "1.8.1"