import { HorizontalBox , VerticalBox, Slider , Button , ScrollView, ComboBox , GridBox} from "std-widgets.slint";
import { Palette } from "../color/palette.slint";
import { CustomSlider } from "slider/slider.slint";

global ScreenCallbacks {
    callback add-box-blur(int);
    callback add-saturation(float);
    callback apply-filters(int, float, float);
    callback reset();
    callback set-Warning-Message(string);
    callback save-file(string);

    callback preview-click(length, length, length, length);
}

component Screen inherits HorizontalBox {
    in-out property <image> image <=> img.source;
    in-out property <length> image-space-size-width <=> img.width;
    in-out property <[string]> histogram: ["","",""];
    property <[color]> h_color: [Colors.red, Colors.green, Colors.blue];
    spacing: 10px;

    left_area := Rectangle {
        background: Palette.Dark.Dark-300;
        border-radius: 7px;
        width: root.width * 20%;
        /*ScrollView {
            width: parent.width;
            padding: 2px;
            x: 0px;*/

            VerticalBox {
                //height: auto;
                width: parent.width;
                spacing: 5px;
                padding: 2px;
                alignment: start;
                h_choice := ComboBox {
                    model: ["R", "G", "B", "all"];
                    current-index: 0;
                    width: 100px;
                    height: 30px;                 
                }
                if 0 <= h-choice.current-index && h-choice.current-index < 3:
                Rectangle {
                    width: parent.width - 30px;
                    height: (root.height - 30px) / 3;
                    //x: 5px;
                    //y: 30px;
                    background: transparent;
                    border-radius: 7px;
                    border-width: 2px;
                    border-color: black;
                    Path {
                        width: parent.width - 5px;
                        height: parent.height - 5px;
                        commands: histogram[h-choice.current-index];
                        stroke: h-color[h-choice.current-index];
                        stroke-width: 1px;
                        fill: self.stroke;
                    }
                }
                if h-choice.current-index == 3: Rectangle {
                    width: parent.width - 30px;
                    height: (root.height - 30px) / 3;
                    //x: 5px;
                    //y: 30px;
                    background: transparent;
                    border-radius: 7px;
                    border-width: 2px;
                    border-color: black;
                    for p in [0, 1, 2] :
                    Path {
                        width: parent.width - 5px;
                        height: parent.height - 5px;
                        commands: histogram[p];
                        stroke: h-color[p].transparentize(0.5);
                        stroke-width: 1px;
                        fill: self.stroke;
                    }
                }
            }
            //viewport-height: (self.width - 10px) * 3;
        //}
    }

    img := Image {
        image-fit: ImageFit.contain;
        TouchArea {
            clicked => {
                ScreenCallbacks.preview-click(
                    self.width, 
                    self.height, 
                    self.pressed-x, 
                    self.pressed-y
                    );
            }
        }
    }

    right_area := VerticalBox {
        width: root.width * 20%;
        padding: 0;
        Rectangle {
            background: Palette.Dark.Dark-300;
            border-radius: 7px;
            GridBox {
                Row {
                    VerticalBox {
                        padding: 5px;
                        Text {
                            text: "saturation: \{saturation.value}";
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            font-size: 10px;
                        }
                        saturation := CustomSlider {
                            //width: right-area.width - 10px;
                            height: 4px;
                            background: @linear-gradient(90deg, #515050 0%, #ff0000 100%);
                        }
                    }
                }
                Row {
                    VerticalBox {
                        padding: 5px;
                        Text {
                            text: "Sharpening: \{sharpening.value}";
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            font-size: 10px;
                        }
                        sharpening := Slider {
                            value: 0;
                            maximum: 1;
                            minimum: 0;
                        }
                    }
                }
                Row {
                    VerticalBox {
                        padding: 5px;
                        Text {
                            text: "Gaussian Blur: \{round(gaussian_blur.value)}";
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            font-size: 10px;
                        }
                        gaussian_blur := Slider {
                            value: 0;
                            maximum: 30;
                            minimum: 0;
                        }
                    }
                }
                Row {
                    VerticalBox {
                        padding: 5px;
                        Text {
                            text: "Box Blur: \{round(box_blur.value)}";
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            font-size: 10px;
                        }
                        box_blur := Slider {
                            //width: right-area.width - 10px;
                            value: 0;
                            maximum: 30;
                            minimum: 0;
                        }
                    }
                }
                Row {
                    Button {
                        text: "apply filters";
                        clicked => {
                            ScreenCallbacks.apply-filters(box-blur.value, gaussian-blur.value, sharpening.value);
                        }
                    }
                }
                Row {
                    Button {
                        text: "apply saturation";
                        clicked => {
                            ScreenCallbacks.add-saturation(saturation.value);
                        }
                    }
                }
                Row {
                    Button {
                        text: "Reset";
                        clicked => {
                            saturation.value = 0;
                            box-blur.value = 0;
                            ScreenCallbacks.reset();
                        }
                    }
                }
                Row {
                    HorizontalBox {
                        tx := TextInput {
                            text: "prova.jpg";
                        }
                        Button {
                            text: "Save";
                            clicked => {
                                ScreenCallbacks.save-file(tx.text)
                            }
                        }
                    }
                }
            }
        }
    }
}

export { Screen, ScreenCallbacks }