import { HorizontalBox , ListView, ScrollView, VerticalBox} from "std-widgets.slint";
import { Palette } from "..\\color\\palette.slint";
import { MenuItem, PopupMenu, Spacer } from "menu\\menu.slint";

global ToolbarCallbacks {
    callback open_file_callback();
    callback close_window_callback();
}

component ToolbarButton inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;

    border-color: transparent;
    background: Palette.Primary.Primary-500;
    border-radius: 7px;
    width: 50px;

    txt := Text{
        x: (parent.width - self.width)/2;
        y: (parent.height - self.height)/2;
        color: black;
    }

    touch := TouchArea{}
}

component Toolbar inherits Rectangle {
    background: transparent;
    height: 25px;

    tb := HorizontalBox {
        height: parent.height;
        width: parent.width;
        padding: 7px;

        x: 0px;
        y: 0px;
        
        file_popup := PopupMenu {
            x: file-button.x;
            y: parent.height;
            MenuItem {
                text: "New project";
            }
            Spacer {}
            MenuItem {
                item-callback => { ToolbarCallbacks.open-file-callback(); }
                text: "Open a file";
            }
            Spacer { size: 2px; }
            MenuItem {
                text: "Close window";
                item-callback => { ToolbarCallbacks.close-window-callback(); }
            }
        }

        file_button := ToolbarButton {
            text: "Files";
            clicked => {
                file-popup.show()
            }
        }

        ToolbarButton {
            text:"Edit";
        }
    }
}

export { Toolbar, ToolbarCallbacks }