global Palette {
    in-out property <{
        Dark-100: color, Dark-200: color, Dark-300: color, 
        Dark-400: color, Dark-500: color, Dark-600: color}> Dark:{
            Dark-100: #121212, Dark-200: #282828, Dark-300: #3f3f3f, 
            Dark-400: #575757, Dark-500: #717171, Dark-600: #8b8b8b,
        };
    in-out property <{
        Primary-100: color, Primary-200: color, Primary-300: color, 
        Primary-400: color, Primary-500: color, Primary-600: color}> Primary: {
            Primary-100: #382bf0, Primary-200: #5e43f3, Primary-300: #7a5af5,
            Primary-400: #9171f8, Primary-500: #a688fa, Primary-600: #ba9ffb,
        };
}

export { Palette }