from typing import Tuple

def adjust_saturation(
    buffer: list[list[float]], added_value: float
) -> list[list[float]]: ...
def adjust_exposure(
    buffer: list[list[float]], added_value: float
) -> list[list[float]]: ...
def convert_to_grayscale(buffer: list[list[float]]) -> list[float]: ...
def combine_grayscale_with_colored(
    grayscale_buffer: list[float], buffer: list[list[float]]
) -> list[list[float]]: ...
def adjust_contrast(
    buffer: list[list[float]], added_value: float
) -> list[list[float]]: ...
def crop_image(
    buffer: list[list[float]],
    image_size: Tuple[int, int],
    crop: Tuple[int, int, int, int],
) -> list[list[float]]: ...
def find_edges_mask(
    buffer: list[float], image_size: Tuple[int, int], sigma: float, size: int
) -> list[float]: ...
def collect_data(
    buffer: list[list[float]], data_type: str
): ...